from dataclasses import dataclass
from typing import Iterable, TypeAlias

import numpy as np

from ..rng import Seed
from .meta import (
    ConcreteValue,
    Data,
    Phase,
    Plate,
    PlateLayout,
    PlateSizes,
    Scalar,
    ValueMeta,
    ValueSupport,
)
from .ops import Reduction

@dataclass(frozen=True, slots=True)
class Dependency:
    role: str
    node: RandomVariable

class RandomVariable:
    def dependencies(self) -> tuple[Dependency, ...]: ...

    @property
    def plates(self) -> frozenset[Plate]: ...
    @property
    def plates_ordered(self) -> tuple[Plate, ...]: ...
    @property
    def plate_layout(self) -> PlateLayout: ...
    @property
    def pending_phases(self) -> frozenset[Phase]: ...
    @property
    def has_value(self) -> bool: ...
    @property
    def value_meta(self) -> ValueMeta: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def support(self) -> ValueSupport: ...

    def value(
        self,
        plate_sizes: PlateSizes | None = ...,
    ) -> ConcreteValue: ...

    def add_plates(
        self,
        *plates: Plate,
        expect: Iterable[Plate] | None = ...,
    ) -> RandomVariable: ...
    def check_plates(self, *plates: Plate) -> RandomVariable: ...
    def reduce_plates(
        self,
        *plates: Plate,
        reduction: Reduction,
    ) -> RandomVariable: ...
    def mean(self, *plates: Plate) -> RandomVariable: ...
    def sum(self, *plates: Plate) -> RandomVariable: ...
    def max(self, *plates: Plate) -> RandomVariable: ...
    def min(self, *plates: Plate) -> RandomVariable: ...
    def prod(self, *plates: Plate) -> RandomVariable: ...
    def logsumexp(self, *plates: Plate) -> RandomVariable: ...

    def materialize(
        self,
        *,
        seed: Seed | None = ...,
        plate_sizes: PlateSizes | None = ...,
        phases: Iterable[Phase] | None = ...,
    ) -> RandomVariable: ...
    def realize(
        self,
        *,
        seed: Seed | None = ...,
        plate_sizes: PlateSizes | None = ...,
    ) -> ConcreteValue: ...

    def structurally_equal(self, other: RandomVariable) -> bool: ...
    def stochastically_equal(self, other: RandomVariable) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

    def __add__(self, other: ExprInput) -> RandomVariable: ...
    def __radd__(self, other: ExprInput) -> RandomVariable: ...
    def __sub__(self, other: ExprInput) -> RandomVariable: ...
    def __rsub__(self, other: ExprInput) -> RandomVariable: ...
    def __mul__(self, other: ExprInput) -> RandomVariable: ...
    def __rmul__(self, other: ExprInput) -> RandomVariable: ...
    def __truediv__(self, other: ExprInput) -> RandomVariable: ...
    def __rtruediv__(self, other: ExprInput) -> RandomVariable: ...

class Constant(RandomVariable):
    def __init__(
        self,
        value: Data,
        *plates: Plate,
        meta: ValueMeta | None = ...,
    ) -> None: ...

ExprInput: TypeAlias = RandomVariable | Scalar

def as_random_variable(expr: ExprInput) -> RandomVariable: ...
