from enum import Enum
from typing import Protocol

import numpy as np

from .meta import ValueMeta, ValueSupport

class BinaryOperator(str, Enum):
    ADD: str
    SUBTRACT: str
    MULTIPLY: str
    TRUE_DIVIDE: str

class UnaryOperator(str, Enum):
    EXP: str
    LOG: str
    SOFTPLUS: str

class Reduction(str, Enum):
    MEAN: str
    SUM: str
    MAX: str
    MIN: str
    PROD: str
    LOGSUMEXP: str

class BinOpImpl(Protocol):
    @property
    def kind(self) -> BinaryOperator: ...
    def resolve_meta(self, lhs: ValueMeta, rhs: ValueMeta) -> ValueMeta: ...
    def compute_value(self, lhs: np.ndarray, rhs: np.ndarray) -> np.ndarray: ...

class UnaryOpImpl(Protocol):
    @property
    def kind(self) -> UnaryOperator: ...
    def resolve_meta(self, child: ValueMeta) -> ValueMeta: ...
    def compute_value(self, child: np.ndarray) -> np.ndarray: ...

class ReductionImpl(Protocol):
    @property
    def kind(self) -> Reduction: ...
    def resolve_meta(self, child: ValueMeta) -> ValueMeta: ...
    def resolve_support(self, child: ValueSupport) -> ValueSupport: ...
    def compute_value(
        self,
        child: np.ndarray,
        *,
        axes: tuple[int, ...],
    ) -> np.ndarray: ...

class AddOp(BinOpImpl): ...
class SubtractOp(BinOpImpl): ...
class MultiplyOp(BinOpImpl): ...
class TrueDivideOp(BinOpImpl): ...

class ExpOp(UnaryOpImpl): ...
class LogOp(UnaryOpImpl): ...
class SoftplusOp(UnaryOpImpl): ...

def binary_op_impl(kind: BinaryOperator) -> BinOpImpl: ...
def unary_op_impl(kind: UnaryOperator) -> UnaryOpImpl: ...
def reduction_impl(kind: Reduction) -> ReductionImpl: ...
