class StochasticProgrammingError(Exception): ...


class GraphValidationError(StochasticProgrammingError): ...


# Legacy duplicate-name error intentionally retired. Explicit RNG-key reuse is
# now an opt-in request for shared deterministic randomness.
#
# class DuplicateRNGNameError(GraphValidationError): ...


class GraphCycleError(GraphValidationError): ...


class PlateError(StochasticProgrammingError): ...


class DuplicatePlateError(PlateError): ...


class PlateExpectationError(PlateError): ...


class UnknownPlateError(PlateError): ...


class MissingPlateSizeError(PlateError): ...


class PhaseError(StochasticProgrammingError): ...


class MaterializationError(StochasticProgrammingError): ...


class BackendError(MaterializationError): ...


class InvalidSupportError(BackendError): ...


class UnrealizedGraphError(MaterializationError): ...


class PlateSizeMismatchError(PlateError, MaterializationError): ...


class UnresolvedRandomnessError(MaterializationError): ...
