class StochasticProgrammingError(Exception): ...


class GraphValidationError(StochasticProgrammingError): ...


class DuplicateRNGNameError(GraphValidationError): ...


class GraphCycleError(GraphValidationError): ...


class PlateError(StochasticProgrammingError): ...


class DuplicatePlateError(PlateError): ...


class PlateExpectationError(PlateError): ...


class UnknownPlateError(PlateError): ...


class MissingPlateSizeError(PlateError): ...


class PhaseError(StochasticProgrammingError): ...


class MaterializationError(StochasticProgrammingError): ...


class BackendError(MaterializationError): ...


class UnrealizedGraphError(MaterializationError): ...
