from enum import Enum
from typing import Iterable, Mapping, Sequence, TypeAlias

from .backend import SamplingBackend, Seed

Plate: TypeAlias = str
Phase: TypeAlias = str | None
Scalar: TypeAlias = bool | int | float

class Reduction(str, Enum):
    MEAN: str
    SUM: str
    MAX: str
    MIN: str
    PROD: str
    LOGSUMEXP: str

class Expr:
    @property
    def plates(self) -> frozenset[Plate]: ...
    @property
    def plate_order(self) -> tuple[Plate, ...]: ...
    @property
    def pending_phases(self) -> frozenset[Phase]: ...
    @property
    def enabled_phases(self) -> frozenset[Phase]: ...
    @property
    def is_fully_realized(self) -> bool: ...

    def add_plates(
        self,
        *plates: Plate,
        expect: Iterable[Plate] | None = ...,
    ) -> Expr: ...
    def check_plates(self, *plates: Plate) -> Expr: ...
    def reduce_plates(
        self,
        *plates: Plate,
        reduction: Reduction,
    ) -> Expr: ...
    def mean(self, *plates: Plate) -> Expr: ...
    def sum(self, *plates: Plate) -> Expr: ...
    def max(self, *plates: Plate) -> Expr: ...
    def min(self, *plates: Plate) -> Expr: ...
    def prod(self, *plates: Plate) -> Expr: ...
    def logsumexp(self, *plates: Plate) -> Expr: ...

    def materialize(
        self,
        *,
        seed: Seed,
        backend: SamplingBackend | None = ...,
        plate_sizes: Mapping[Plate, int] | None = ...,
        phases: Iterable[Phase] | None = ...,
    ) -> Expr: ...
    def realize(
        self,
        *,
        seed: Seed,
        backend: SamplingBackend | None = ...,
        plate_sizes: Mapping[Plate, int] | None = ...,
    ) -> object: ...
    def assert_fully_realized(self) -> Expr: ...
    def value(self) -> object: ...

    def structurally_equal(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

    def __add__(self, other: ExprInput) -> Expr: ...
    def __radd__(self, other: ExprInput) -> Expr: ...
    def __sub__(self, other: ExprInput) -> Expr: ...
    def __rsub__(self, other: ExprInput) -> Expr: ...
    def __mul__(self, other: ExprInput) -> Expr: ...
    def __rmul__(self, other: ExprInput) -> Expr: ...
    def __truediv__(self, other: ExprInput) -> Expr: ...
    def __rtruediv__(self, other: ExprInput) -> Expr: ...

class Constant(Expr):
    def __init__(
        self,
        value: object,
        *,
        plates: Sequence[Plate] = ...,
    ) -> None: ...

ExprInput: TypeAlias = Expr | Scalar
