# Legacy Expr-named transform signatures, retained for design history.
#
# from .expr import Expr, ExprInput
#
# def exp(expr: ExprInput) -> Expr: ...
# def log(expr: ExprInput) -> Expr: ...
# def softplus(expr: ExprInput) -> Expr: ...

from .expr import ExprInput, RandomVariable

def exp(expr: ExprInput) -> RandomVariable: ...
def log(expr: ExprInput) -> RandomVariable: ...
def softplus(expr: ExprInput) -> RandomVariable: ...
